input_data_config:
  security_code_list: [300308, 603288, 300394, 600557]
task_config:
  prompts_path_list:
    [
      summary/report_manager_ana/company_core/v1,
      summary/report_manager_ana/industry/v1,
      summary/report_manager_ana/key_danger/v1,
      summary/report_manager_ana/operation/v1,
      summary/report_manager_ana/danger/v1,
    ]
mongo_config:
  host: 127.0.0.1
  password: OTNmYTdjYmZkMjE5ZmYzODg0MDZiYWJh
  user: root
  port: 27007
open_ai_key: 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
