version: '2'
services:
  redis:
    image: redis:latest
    volumes:
      - ./db/redis:/data/cache
    ports:
      - "6369:6379"
    environment:
      - REDIS_PASSWORD=myredispassword
    command: [ "redis-server", "--requirepass", "myredispassword" ]
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: OTNmYTdjYmZkMjE5ZmYzODg0MDZiYWJh
    volumes:
      - ./db/mongo:/data/db
      - ./db/mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27007:27017"
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8071:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: OTNmYTdjYmZkMjE5ZmYzODg0MDZiYWJh
